server:
  port: 8081

spring:
  #MySQL 연동
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: wlstn4050!

  #JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  #ddl-auto 옵션
  #jpa의 database 초기화 전략
  #none : 아무것도 실행하지 않음
  #create-drop : SessionFactroy 시작 시점에 drop 후 create를 실행하며, SessionFactory 종료시 drop을 실행함
  #update : 변경된 스키마를 적용
  #create : SessionFactory 시작 시점에 drop을 실행하고 create를 실행
  #validate : 변경된 스키마가 존재하면 변경사항을 출력하고 app을 종료

  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: mkjs0309@gmail.com
    password: pxcpoaxkgwyenryh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

api:
  naver:
    client_id: K9TJfmrbHamf0arWWpQa
    client_secret: Kkea5WMC2K